
name: 'dbt_superset'
version: '0.1.0'
require-dbt-version: ['>=1.3.0']
config-version: 2
profile: 'dbt_superset'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_superset:
    example:
      +materialized: view

vars:
  superset_source_schema: "superset_raw"
  superset_target_tz: "UTC"
  superset_source_tz: "UTC"

